### ISSUE TITLE
Increase timeout for waiting for DIC result in request process

### ISSUE THREAD

**Issue by EmteZogaf** [medizininformatik-initiative/feasibility-dsf-process#86]
Currently the request process has a 30 seconds timeout waiting for each result after sending the feasibility execute tasks to each DIC. This should be increased to 5 minutes to accommodate for long running or non-cached queries in the DIC.

**Comment by juliangruendner** [comment]
Additional Explanation:
The feasibility plugin send a feasibility request to all DIC and waits for TIMEOUT seconds for a response from each DIC.
If a DIC does not answer within this timeout the answer will be lost.
The Timeout should match the timeout in the feasibility backend so that the answers which a received within the configured time are still processed by the DSF
